### ISSUE TITLE
Documentation: add ids of datapoints to be logged in influxdb

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [Seqway/Grafana-Dashboards#1]
Add

> the following datapoints need to be anabled for influxDB logging
javascript.0.Speedtest.Ergebnisse.Download_MB
javascript.0.Speedtest.Ergebnisse.Download_MBit
javascript.0.Speedtest.Ergebnisse.Ping
javascript.0.Speedtest.Ergebnisse.Upload_MB
javascript.0.Speedtest.Ergebnisse.Upload_MBit

**Comment by Seqway** [comment]
Documentation is updated accordingly ! Thank you !
